/**
 * Blog post metadata + content. Sourced from the live site at
 * https://www.jimmullaney.com/ — the owner of that site is also the owner
 * of this clone project. Each post is indexed by (year, month, slug) for
 * the dynamic route.
 */

export type BlogPost = {
  year: string;
  month: string;
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  body: string[];
};

export const posts: BlogPost[] = [
  {
    year: "2026",
    month: "03",
    slug: "dividing-high-value-real-estate-in-an-uncontested-jacksonville-divorce",
    title: "Dividing high-value real estate in an uncontested Jacksonville divorce",
    date: "March 6, 2026",
    excerpt: "Jacksonville's luxury real estate market is booming in historic Avondale and the serene Atlantic Beach coastline.",
    body: [
      "Jacksonville's luxury real estate market is booming in historic Avondale and the serene Atlantic Beach coastline. When you end a marriage, these high-value properties represent significant financial investments.",
      "Even in an uncontested divorce, you must address equity and debt with precision. Failing to do so can result in costly tax consequences or title disputes.",
      "Funding the departure and managing debt",
      "In many Jacksonville divorces, one spouse stays in the family home while the other moves on, usually requiring a \"buy-out\" in which the staying spouse pays the other spouse for their portion of the home's current value. High property values mean these payments often reach six or seven figures.",
      "To make this work, the spouse keeping the home typically must refinance the mortgage. This process severs the financial tie between the former partners. Consider these standard lender requirements:",
      "- The staying spouse must qualify for a new loan using their own income and any qualifying court-ordered support.\n- The new loan must cover both the old mortgage balance and the agreed-upon buy-out amount.\n- Recent interest rate hikes may significantly increase the monthly cost of keeping a beachfront property.\n- Refinancing officially removes the departing spouse from the debt obligation.",
      "Without a new mortgage, both people remain legally responsible for the debt even if they are no longer married. Completing the refinancing process ensures your credit remains protected.",
      "Formalizing ownership with property deeds",
      "Once you agree on who stays, you must legally change the name on the property title. A quitclaim deed is a common tool in Florida, though a properly drafted final divorce judgment can also transfer title. Both methods require precise legal descriptions to avoid future ownership conflicts.",
      "You must follow specific steps to ensure the transfer is valid under Florida law. Errors in this stage can complicate future sales or refinancing. Keep these requirements in mind:",
      "- Sign and notarize the deed in accordance with Florida state statutes.\n- Record the deed or final judgment with the Duval County Clerk of the Circuit Court's Recording Department.\n- Remember that a deed transfers ownership but does not satisfy the mortgage company's debt requirements.\n- Verify that your marital settlement agreement matches the language used in your transfer documents.",
      "The timing of this transfer matters to prevent future title disputes. Proper documentation ensures that your real estate transition remains as peaceful as the rest of your filing.",
      "Protect your financial future",
      "Finalizing an uncontested divorce involving high-value assets requires a clear marital settlement agreement. Vague language about sale dates or appraisal methods can lead to arguments or litigation years later.",
      "Guidance from a skilled divorce lawyer ensures your paperwork is enforceable and legally sound. Your attorney helps you navigate complex title issues to safeguard your financial interests. They provide the peace of mind you need to start your next chapter.",
    ],
  },
  {
    year: "2026",
    month: "03",
    slug: "the-kitchen-table-divorce-turning-your-verbal-agreement-into-a-legal-reality",
    title: "The \"kitchen table\" divorce: turning your verbal agreement into a legal reality",
    date: "March 5, 2026",
    excerpt: "It is something that happens more frequently than you might think: a couple sits down to have a conversation, have a meal or a drink and then simply agree to separate.",
    body: [
      "It is something that happens more frequently than you might think: a couple sits down to have a conversation, have a meal or a drink and then simply agree to separate. Arrangements are easily smoothed out and suddenly everything is taken care of.",
      "A \"handshake deal\" like this is a huge relief for a couple. But a verbal agreement does not mean an official divorce. To protect your future and ensure your agreement is followed, you must turn that amicable moment into a legally binding judgement.",
      "Your handshake needs a paper trail",
      "Trust is a great starting point, but conditions change. Without a formal Marital Settlement Agreement (MSA) and a court order:",
      "- **Property stays in limbo:** You cannot legally force a deed transfer or a home sale.\n- **Retirement is off-limits:** You cannot divide a 401(k) or pension without a Qualified Domestic Relations Order (QDRO).\n- **Custody is unenforceable:** Police cannot enforce a parenting schedule without a judge's signature.",
      "A common risk of informal agreements is the inability to modify them when life changes. In Florida, if your circumstances shift (such as a significant change in income or a need to relocate) a verbal deal offers no path for adjustment. By formalizing your agreement through an MSA, you establish a legal baseline. This allows you to return to court in the future to request modifications to alimony or child support through official channels, a protection that simply does not exist with a handshake.",
      "The state court process",
      "Even if you agree on everything, Florida law requires certain steps to be followed before a judge will officially dissolve a marriage:",
      "- **Mandatory disclosure:** Even in an uncontested divorce, both parties must exchange financial affidavits. This ensures the agreement is fair and based on full transparency.\n- **The drafting phase:** We ensure the division of assets follows Florida's equitable distribution principles while staying true to your specific wishes.\n- **The final hearing:** In many uncontested Jacksonville cases, the court process can be streamlined. Once the judge reviews the MSA and is satisfied that it meets legal standards, they will sign the final judgment of dissolution of marriage.",
      "By turning your handshake into a court order, you are providing yourselves with the gift of certainty and a clean break, allowing both of you to move forward with the peace of mind that your agreement is protected by law. You can contact an attorney so they can make all necessary arrangements.",
    ],
  },
  {
    year: "2026",
    month: "01",
    slug: "the-divorce-finish-line-how-fast-can-we-really-get-an-uncontested-divorce-in-florida",
    title: "The Divorce Finish Line \u2013 How Fast Can We Really Get an Uncontested Divorce in Florida?",
    date: "January 12, 2026",
    excerpt: "An uncontested divorce in Florida is typically faster than a contested divorce. It means that you and your spouse already agree on many of the terms of that divorce, such as how\u2026",
    body: [
      "An uncontested divorce in Florida is typically faster than a contested divorce. It means that you and your spouse already agree on many of the terms of that divorce, such as how to divide marital assets or how to split up custody of your children. A contested divorce that has to be litigated in court is going to take much longer because both sides have to attend hearings, present their arguments and get a ruling from a judge.",
      "But just how fast can you end your marriage? There are a few different deadlines to consider.",
      "Residency requirements",
      "To begin with, note that Florida has residency requirements stating that either you or your spouse must have lived within the state for six months prior to filing. So if you just moved to Florida, you cannot even start the process for half a year. But if you have lived in Florida all of your life, you naturally meet these residency requirements already.",
      "The waiting period",
      "Additionally, Florida has a mandatory waiting period of 20 days. This means that the court is not even allowed to issue an official divorce until 20 days have elapsed between the filing and the finalization.",
      "Similarly, once you file for divorce and serve the papers to your spouse, they have 20 days to respond. Even if they never respond, you still have to wait those 20 days before you can move forward with a default divorce. In an uncontested divorce, it is likely that your spouse will respond relatively quickly because it is an amicable process, but the 20-day mandatory waiting period still applies. The court cannot legally finalize your divorce any faster than that, even if you and your spouse agree on every single detail.",
      "The court process",
      "Finally, the speed of the divorce may depend on the court system in Florida. If the court has a backlog of other cases to handle, it can take time simply to get a hearing and take other necessary steps before the divorce is finalized. So it is not all up to you and your spouse, or the fact that you are filing an uncontested divorce. At the end of the day, it generally takes a minimum of five to six weeks to end your marriage.",
      "Getting divorced is a major change in your life. It is imperative that you understand all of your rights and legal options, which is why it can be helpful to work with an experienced law firm.",
    ],
  },
  {
    year: "2025",
    month: "06",
    slug: "how-can-uncontested-divorce-provide-a-lower-stress-way-to-end-a-marriage",
    title: "How can uncontested divorce provide a lower-stress way to end a marriage?",
    date: "June 2, 2025",
    excerpt: "Divorce is never easy, but for many couples, an uncontested divorce offers a simpler, more peaceful way to part ways.",
    body: [
      "Divorce is never easy, but for many couples, an uncontested divorce offers a simpler, more peaceful way to part ways. In Florida, choosing an uncontested divorce can provide significant benefits, reducing stress and allowing both parties to move forward with clarity and confidence.",
      "What is an uncontested divorce?",
      "An uncontested divorce occurs when both parties agree on all major issues like their parenting plan, how they will divide their property and any support arrangements. As a result, they can reach an arrangement they believe is fair without the need for court intervention. This type of divorce is typically faster and more straightforward, as it eliminates the need for lengthy litigation and court battles.",
      "Why might you choose an uncontested divorce?",
      "With both parties in agreement, there is less conflict and emotional turmoil. This can be especially beneficial for families with children, as it minimizes the stress and anxiety often associated with divorce.",
      "Agreeing on major issues also allows couples to avoid multiple court appearances and lengthy legal proceedings. This means that, while the divorce will take at least 20 days to complete, couples may complete the divorce process much faster than those who need greater court involvement. This allows both parties to move on with their lives more quickly and with less disruption.",
      "In addition to resolving more quickly, an uncontested divorce is generally more affordable than a contested one. By avoiding drawn-out court battles and reducing legal fees, couples can save money. This allows them to dedicate those resources to rebuilding their lives post-divorce.",
      "Finally, couples retain control over the terms of their divorce. This allows them to tailor agreements to their specific needs and circumstances. This autonomy can lead to more satisfactory outcomes for both parties.",
      "You can work toward a brighter future",
      "An uncontested divorce in Florida offers a peaceful and efficient way for couples to separate, prioritizing mutual agreement and simplicity. By choosing this path, individuals can achieve a sense of closure and begin the next chapter of their lives with peace of mind.",
    ],
  },
  {
    year: "2016",
    month: "06",
    slug: "4-common-life-changes-after-divorce",
    title: "4 Common Life Changes After Divorce",
    date: "June 14, 2016",
    excerpt: "When many couples divorce, they expect their Parenting Plan to cover the time-sharing for their child until the child has graduated from high school.",
    body: [
      "When many couples divorce, they expect their Parenting Plan to cover the time-sharing for their child until the child has graduated from high school. While that is possible, that might not be in the best interests of their child. Also, the day-to-day lives of the parents can change and, as a result, the terms of the Parenting Plan become unworkable. The following are six common post-divorce problems that can (and maybe should) effect time sharing.",
      "- **Remarriage** \u2013 It is important to consider the impact that a parent's new romantic relationship will have on the child. Each child will react differently in such a situation. The timing and frequency of these types of events can also have an impact on the child. It may be wise to consult with a mental health professional before (or during) making too many big changes too quickly.\n- **Job Loss** \u2013 Often, unforeseen circumstances lead to one, or both, parents losing their job. Just as it would if the parents were still together, job loss has a big impact on the lives of both parents and the child. Due to the loss of income, a parent receiving child support may be able to have the other parent's child support obligation increased. Similarly, a parent who pays child support can potentially have their child support obligation reduced due to their loss or reduction in income (while including unemployment or severance pay). Whether you think the child support should be increased or decreased, it is important to ask the court to make a change. Modifications are usually only retroactive to the date the parent asked to court to make the change \u2013 not the date they lost their job.\n- **Relocation** \u2013 Obviously, moving the child far away from a parent who has been involved in the child's life will impact that relationship and the child. The Florida Statutes require either court permission or the other party's consent when a relocation of more than 50 miles is proposed.\n- **Changing Needs of the Child** \u2013 A child's needs change as they get older. What might have worked great for a 2-year-old child might not meet the needs of a 12 or 17-year-old child. It's common for one parent to be the primary caregiver for a small child. A 50/50 time-sharing arrangement might not work well for a 2-3 year old child. However, such a schedule might be better for a teenager. Perhaps a child could benefit from an amended schedule due to academic reasons or involvement in extracurricular activities. It is also important to note than a change in the time-sharing schedule may involve a change in the child support amount since the number of nights that each parent spends with the child is a factor in the child support calculation.",
    ],
  },
  {
    year: "2016",
    month: "05",
    slug: "4-questions-to-ask-before-filing-for-divorce",
    title: "4 Questions to Ask Before Filing for Divorce",
    date: "May 26, 2016",
    excerpt: "No one other than you can answer the question, \"Should I get a divorce?\" The effects of a divorce will be felt for many years \u2013 longer if you have children with your spouse.",
    body: [
      "No one other than you can answer the question, \"Should I get a divorce?\" The effects of a divorce will be felt for many years \u2013 longer if you have children with your spouse. While there may be many questions you need to ask yourself, the following questions are a good start:",
      "Have you done everything you can to try to save your marriage?",
      "Have you tried to save your marriage? This could mean anything from reading self-help books to attending counseling with (or without) your spouse. You owe it to yourself \u2013 and any children \u2013 to learn if anything can be done to save your marriage.",
      "In order to get a divorce in Florida, the law requires that your marriage be irretrievably broken. This is a complicated way of saying \"broken and cannot be fixed.\" Very often this requires no more proof than saying, \"my marriage is irretrievably broken.\" But, the judges take this requirement seriously and want to know if you have tried everything to save your marriage.",
      "Are you effectively dealing with the emotions that are associated with divorce?",
      "A divorce can bring up intense emotions. Among these are hurt feelings, guilt, confusion, anger, and maybe relief. It's important that you are at (or near) your best as you go through a divorce since many decisions will be made that could affect the rest of your life. If you are having trouble dealing with various emotions, you should seek the help of a professional counselor.",
      "Have you researched how to get divorced?",
      "Everyone knows that they can get divorced. But, do you know how to get divorced? Are you planning on handling the legal aspects of your case by yourself? Do you know a divorce lawyer? Do you know how much an uncontested case costs as compared to a contested case? Do you know how long a divorce will take? If you and your spouse cannot agree on the terms of a divorce, have you considered mediation prior to starting the divorce case in order to keep the costs down?",
      "Are you ready to be single again?",
      "Especially for those who end long marriages after getting married relatively young, transitioning to single life can be challenging. Do you have a budget? If you have children, are you ready to co-parent those children with your ex? Being since means more than the absence of your spouse. It brings a whole \u2013 often new \u2013 set of challenges.",
      "Since you are the only one that can answer these questions, it is important to consider the answers before moving forward with a divorce.",
    ],
  },
  {
    year: "2017",
    month: "03",
    slug: "changes-to-required-parenting-class-in-north-florida",
    title: "Changes to Required Parenting Class in North Florida",
    date: "March 14, 2017",
    excerpt: "Florida law has long required divorcing couples with children to attend a \"Parent Education and Family Stabilization\" class aimed at educating the parents about the special\u2026",
    body: [
      "Florida law has long required divorcing couples with children to attend a \"Parent Education and Family Stabilization\" class aimed at educating the parents about the special challenges that await children of those divorcing couples. Parents involved in a paternity case are also required to take the class. In Duval County, this class, Children First in Divorce, has been offered by the Hope Haven Children's Clinic and Family Center for over 20 years.",
      "Just last month the Chief Judge of the Fourth Judicial Circuit (Duval, Clay, and Nassau Counties) made a few changes to the requirements that parents take this class. First, the class has been renamed to Two Parents, Two Homes. This change, while seemingly simple, will clear up the confusion experienced by many parents involved in a paternity case where they think the Children First in Divorce does not apply to them since the title contains the word \"divorce.\"",
      "It has long been the practice of the family court judges in Duval county to require that parents take the class in person rather than online. I always specifically tell new clients to take the live class rather than an online class even though the online class is advertised as \"accepted by all courts in the State of Florida.\" In general, there is an exception allowed where a parent does not live in the area. However, the new rules require that a parent wishing to take a class other than Two Parents, Two Homes, must have **prior approval** from the judge before enrolling in the class of their choice. Whether a judge will allow an outside class will be determined on a case-by-case basis.",
    ],
  },
  {
    year: "2017",
    month: "07",
    slug: "does-divorce-hurt-your-credit-score",
    title: "Does Divorce Hurt Your Credit Score?",
    date: "July 1, 2017",
    excerpt: "Does divorce hurt your credit score? The quick answer is \"yes.\" But only in some situations.",
    body: [
      "Does divorce hurt your credit score? The quick answer is \"yes.\" But only in some situations.",
      "Your credit score is not automatically affected by your divorce. The Clerk of Court does not notify the credit bureaus that you are no longer married.",
      "Your credit score is hurt when your debts are not paid in a timely manner. At the end of a divorce case, you will probably end up being responsible for some \u2013 or all \u2013 of the debts in your name as well as some \u2013 or all \u2013 of the joint debts.",
      "Joint debts are debts that both you and your spouse agreed to be responsible for when you created the account. Examples of potential joint debts are mortgages, joint credit cards (not where your spouse is just an authorized user), car loans, and apartment rentals. Your relationship with the creditor or lender is not affected by your divorce order.",
      "For example, suppose that a Husband and Wife have a joint credit card that they owe $5,000.00 on. They both signed the credit application. If they stop paying the credit card bill while married, both of their credit scores will be hurt. Now assume that when they get divorced, the judge orders the Husband to pay the entire $5,000.00 credit card balance. When and if he stops paying the credit card bill as ordered, both the Husband's and the Wife's credit score will be affected. The Wife is not absolved of her obligation to the credit card company by the divorce order. The rights of the lender are not affected by the couple's divorce case. The credit card company can (and will) try to recover whatever it can from both the Husband and the Wife. This is called joint and several liability.",
      "Now suppose that the credit card, above, was only in the Husband's name. When the couple gets a divorce, the judge could require the Wife to pay a portion of the credit card balance. If she fails to pay what the judge ordered, her credit will not be affected \u2013 since she has no legal/contractual relationship with the credit card company. However, the Wife could be sued by her then ex-Husband for the extra amount he had to pay. Any judgment rendered against her could hurt her credit rating.",
      "If you are thinking about a divorce, consider closing joint accounts in order to minimize the impact to your credit score if your spouse fails to pay what they owe. Also, be on the lookout for unusual activity on your credit card or a joint credit card. Unfortunately, it is common for one spouse to make excessive purchases prior to a divorce.",
      "Lastly, when negotiating a division of your assets and debts, consider taking on a higher amount of the joint debts if you can get a similar amount of the marital assets. If successful, your credit score could only be hurt if you fail to pay the debts.",
    ],
  },
  {
    year: "2020",
    month: "01",
    slug: "my-florida-child-support-calculator-new-for-2020",
    title: "My Florida Child Support Calculator \u2013 New for 2020",
    date: "January 10, 2020",
    excerpt: "Why did I create My Florida Child Support Calculator?",
    body: [
      "**Why did I create My Florida Child Support Calculator?**",
      "I often hear from potential clients after they have appeared in court and had their child support calculated. After doing some online research and reviewing the child support guidelines, they went to the hearing without a lawyer. They thought they had a rough estimate of the child support they would be ordered to pay. However, the Florida Child Support Calculator that the Courts use to calculate child support is not even remotely similar to the online calculators. The most common reasons for the difference in child support amounts are:",
      "- The number of nights that each parent spends with their child(ren) is not considered in many online calculators. If you are going to be paying child support and you will have your child(ren) for more than 73 nights per year, then the number of nights is a very important factor in the child support calculation. Simply, if you are the minority time sharing parent, then the more nights you spend with your child(ren), the lower your child support will be. If you are the majority time sharing parent, then the more nights you have your child(ren), the more you can expect to receive in child support.\n- Most online calculators ask for each parent's net income. Even the free forms published by the Supreme Court of Florida ask for net incomes. However, the Courts want to know gross incomes. The Court calculator then calculates your taxes to determine your net income. Consider this example: Suppose you bring home $4,000 per month. When you file your tax return, the IRS gives you a $6,000 refund. If you use an online calculator, you would likely input your income as $4,000.00 per month. The court's calculator would likely use a number closer to $4,500.00 per month. It will consider your tax refund as income. Obviously, the extra $500.00 per month will only increase your child support.\n- The court's calculator will also increase your income if it thinks either (or both) parents receive (or are eligible for) various tax credits. These credits include the Earned Income Credit and the Child Care Credit.",
      "My Florida Child Support Calculator aims to correct these differences the following ways:",
      "- The calculator considers how many nights each parent spends with the child(ren).\n- This calculator asks for your gross income.\n- The calculator computes your federal income tax based on your filing status (married, single, head of household, or married filing separately).\n- This calculator asks you to input your total annual tax credits \u2013 if you have any.",
      "In my over 20 years of family law experience, not once has a client (or potential client) used the Court's calculator themselves. This is most likely because they did not know there was such a program and because the program costs about $600.00 per year to use.",
      "One of my favorite features of my Florida Child Support Calculator is that you can change the various factors used to make the child support calculation (income, day care amount, insurance amount, etc.) and you can see \u2013 in real time \u2013 how that effects the child support amount.",
      "My Florida Child Support Calculator is FREE. I don't know who you are unless you tell me. No bill is coming in the mail! You don't need my permission to use it. You don't need to send me your email address to use it. If you want to send me the results, you can \u2013 but you certainly do not have to.",
      "WARNING: No calculator is perfect. No calculator can take the place of an actual Florida family law attorney. Before you go to court, please consider at least consulting with a Florida family law attorney.",
    ],
  },
  {
    year: "2016",
    month: "04",
    slug: "florida-divorce-family-law-podcast",
    title: "Florida Divorce & Family Law Podcast",
    date: "April 20, 2016",
    excerpt: "Introducing the Florida Divorce & Family Law Podcast.",
    body: [
      "Introducing the Florida Divorce & Family Law Podcast.",
      "Inspired by the podcasters I met and seminars I attended at the 2016 ABA Techshow, I decided to start my own (small) podcast. I will be answering questions related to my practice \u2013 Family Law in Florida. I will try to post two episodes per month. Each episode will run for about 20-30 minutes.",
      "You can find the podcast on iTunes or Overcast (podcast player).",
      "Please feel free to submit a question or offer any feedback.",
    ],
  },
  {
    year: "2015",
    month: "12",
    slug: "how-not-to-get-divorced-advice-not-to-follow",
    title: "How NOT to get Divorced | Advice NOT to follow",
    date: "December 23, 2015",
    excerpt: "This article by California mediator Arianna Jeret lays out the 12 ways to make sure your divorce costs as much as possible.",
    body: [
      "This article by California mediator Arianna Jeret lays out the 12 ways to make sure your divorce costs as much as possible. Great advice for what you absolutely should not do when getting divorced.",
      "- Keep fighting for what is \"fair.\"\n- No matter how comfortable you feel with a settlement proposal, refuse to accept it until your attorney agrees that you should.\n- Demand that your ex run any and all parenting decisions by you until the children are past the age of 18.\n- Insist that your ex undergo a vocational evaluation so you can pay the least amount of child and spousal support over the shortest time period possible.\n- Do your best to ensure that all verbal agreements you and your ex made when during your marriage are honored, regardless of how the court would likely rule on any of the issues at hand.\n- Refuse to settle on each aspect of your divorce agreements until your ex is willing to acknowledge your value, position, opinion, rights, etc.\n- Withhold information requested by your spouse until he or she has agreed to do x, y, or z.\n- Every now and then, attempt to \"negotiate\" with your spouse directly in order to save time and money.\n- Assume that your spouse must be hiding money somewhere and hire a forensic accountant to identify the exact origin of every penny earned and spent by each of you, personally and professionally, over the course of your marriage.\n- Engage a child custody evaluator to decide what is in the best interests of your children. Especially since this group of \"professionals\" is so well known for its ethical procedures, lack of bias, and clean personal backgrounds. Or not.\n- Stay firmly entrenched in a belief or expectation of what you should get in your settlement, particularly as based on a friend's divorce, an article you just read, or a calculator you found online.\n- Decide that you just want to let the judge decide \u2014 despite the fact that in the majority of cases these days many judges simply scare both spouses into going back out into the hallway to come up with a settlement agreement anyway, resulting in a minimum of less than 5% of all cases ever seeing a direct order made by a judge.",
    ],
  },
  {
    year: "2016",
    month: "01",
    slug: "social-security-changes",
    title: "Social Security Changes",
    date: "January 4, 2016",
    excerpt: "There have been big changes recently that may affect the Social Security benefits of divorcing couples.",
    body: [
      "There have been big changes recently that may affect the Social Security benefits of divorcing couples. As either or both spouses age, they are increasingly likely to consider their (and their soon-to-be ex-spouse's) Social Security benefits when going through a divorce.",
      "Previously, a former spouse was able to make an independent decision on when to file for Social Security benefits. Those decisions were based on age, length of the marriage, current marital status, and the entitlement to benefits. For example, you may want to file based on your former spouse's benefits rather than your own if it would entitle you to receive more. Importantly, a potential filer would not have to base their decision on whether their former spouse had already filed for benefits. Unfortunately, that is no longer the case.",
      "Under the revised law, in order to base your benefits on a former spouse, that former spouse must already be receiving benefits. As a result of this change, many divorcing couples will now need to discuss various Social Security claiming scenarios with their lawyer and at their mediation.",
    ],
  },
  {
    year: "2016",
    month: "01",
    slug: "domestic-violence-orders-and-social-media",
    title: "Domestic Violence Orders and Social Media",
    date: "January 18, 2016",
    excerpt: "When a court enters an Order of Protection (against domestic violence, repeat violence, \u2026) a common provision is that the respondent/defendant is prohibited from having any\u2026",
    body: [
      "When a court enters an Order of Protection (against domestic violence, repeat violence, \u2026) a common provision is that the respondent/defendant is prohibited from having any contact with the petitioner/plaintiff. \"No contact\" includes meetings, phone calls, text messages, faxes, email, etc. Included in this prohibition is also having someone contact the petitioner/plaintiff on behalf of the respondent/defendant. For example, it is a violation of the Order of Protection to have a friend tell your former girlfriend that you love her when that girlfriend has an Order of Protection against you.",
      "Recently there have been a few cases where a defendant/respondent has possibly violated the \"no contact\" provision of the Order of Protection by use of social media.",
      "In August, 2105, a Pennsylvania man was arrested for violating that state's version of an Order of Protection after the victim complained to police that her former boyfriend had \"liked\" 22 photos and videos on Facebook. Since he \"liked\" the photos, Facebook generated a notification that informed her of his actions. The man was arrested after the police were informed by the local district attorney that his actions constituted a violation. He was arraigned and released on $5,000 bail.",
      "Recently a New York court held that a woman violated a protection order that prohibited her from having contact with her sister-in-law. The violation occurred when a notification was generated after she \"tagged\" her sister-in-law in a Facebook post. Contact through Facebook was not specifically prohibited, but the judge held that Facebook communication was included in the definition of prohibited \"electronic communication.\" The woman was charged with second degree criminal contempt which could lead to a year long jail term.",
      "The lesson to learn: If an Order of Protection has been placed on you, avoid any potential contact with the person who obtained the Order. It seems that courts will use an expansive interpretation of what is considered to be impermissible contact.",
    ],
  },
  {
    year: "2016",
    month: "02",
    slug: "alimony-deductibility-and-the-irs",
    title: "Alimony Deductibility and the IRS",
    date: "February 16, 2016",
    excerpt: "Whether you pay or receive alimony, the tax implications of alimony are far-reaching.",
    body: [
      "Whether you pay or receive alimony, the tax implications of alimony are far-reaching.",
      "Generally, alimony is taxable as income to the recipient and tax-deductible for the payor. However, the IRS is not bound by a state court order that labels a payment from one party to another as alimony. Simple labeling a payment as alimony in a divorce order is not enough to make the payment tax-deductible to the payor.",
      "Alimony must meet the following requirements in order to be considered tax-deductible by the IRS:",
      "- **The payment must be made from the payor to the payee in cash or its equivalent**. For example, I do not think paying the former spouse's cell phone bill would be considered alimony.\n- **The payor and the payee cannot live together.** Otherwise, couples could divorce while remaining in the same home in order to reduce their taxes since the lower-earning spouse's income is generally taxed at a lower rate than the higher-earning spouse.\n- **The payments must terminate upon the death of the payee.** While most alimony payments also terminate when the payor dies, this is not a requirement. Very often life insurance proceeds can take the place of alimony payments after a payor dies.\n- **The court order that requires the alimony cannot state that the alimony is non-deductible to the payor and non-taxable to the payee**. So, essentially, it is easy to make the alimony payments non-deductible to the payor (and non-taxable to the payee) by simply stating so in the court order.\n- **Payments must be made pursuant to a court order**. In Florida, this includes a final order in a divorce (dissolution of marriage) case or a separate maintenance order. In short, a separate maintenance case is brought by one spouse that asks the court to order the other spouse to provide support (child support or alimony or both) without asking for a dissolution of the marriage. I do not believe that a written agreement between the parties (e.g. a port-nuptial agreement) is sufficient. A judge's signature is required.\n- **The payors tax return must include the payee's Social Security number.** This is so the IRS can verify that someone is paying taxes on the income. A payee that does not include alimony they have received on their tax return will almost certainly be contacted by the IRS and be responsible for the additional tax (along with penalties and interest).",
      "At the Law Office of A. James Mullaney, we use software that estimates your taxes if alimony payments are made in your case. Since alimony paid or received affects the incomes of the parties, alimony affects any child support calculation as well.",
    ],
  },
  {
    year: "2016",
    month: "03",
    slug: "client-file-security",
    title: "Client File Security",
    date: "March 11, 2016",
    excerpt: "Think about all the documents that exist in a client's file: court filings, financial affidavits, correspondence to and from clients and opposing counsel, bank records, credit\u2026",
    body: [
      "Think about all the documents that exist in a client's file: court filings, financial affidavits, correspondence to and from clients and opposing counsel, bank records, credit card bills, tax returns, pay stubs, and insurance (car, home, health, life) information.",
      "Occasionally, a client will ask: \"How are my documents stored?\"",
      "This article is a description of the steps I take to safeguard your private information.",
      "First, a little background on what happens with your private document that you give me:",
      "Court documents \u2013 these are the documents that I prepare and that you and/or I sign before they are filed with the clerk of Court electronically. Copies are electronically sent to the opposing party or their lawyer. These documents are scanned when received and shredded at the end of your case. The digital version of the file is retained.",
      "Discovery documents \u2013 these are the documents that must be produced so they can be reviewed by the other party or their lawyer. Typically, these documents include bank records, credit card bills, tax returns, pay stubs, and insurance (car, home, health, life) information. Similar information is received from the opposing party. These documents are also scanned when received and shredded at the end of your case. Of course, I'd be happy to return your discovery documents to you at the end of your case.",
      "So, how do I protect the digital versions of your private information?",
      "First, I encrypt the hard drive of the computer that I use for running my law firm. I use FileVault (a program built in the Mac operating system). If my computer is stolen, all data on the hard drive is inaccessible to the thief without the encryption key. You data is just as safe as any of my own personal information on the hard drive. The thieves may have my computer, but your data is locked inside and they don't have a key.",
      "The thieves could try to automate the guessing of the encryption key. Even if they had a computer that could guess 4 billion passwords per second, it would take 12 trillion years, on average, to guess the correct 16 (or fewer) character password!",
      "Second, the hard drive inside my computer is backed up to the online service BackBlaze. So, if my hard drive fails or is stolen, all data can be retrieved from the backup. The BackBlaze program encrypts all data with an encryption key before it is transmitted from my computer over a secure SSL (https) connection to their system. The data is stored in encrypted form. In theory, since BackBlaze has the encryption key, they could view your data. However, I have elected to use an additional security feature that they offer by encrypting their key with a phrase that I choose. That way, they cannot ever view your data.",
      "Third, your documents are accessible on my various devices via Dropbox. They are never stored on these devices, but can be viewed and edited since all the files are synced via DropBox. So, your documents exist on my computer and on the Dropbox servers. Dropbox encrypts your data as it it in transit and when it is on their servers. They hold the encryption key.",
      "Fourth, I remove the ability of Dropbox to view the contents of your files. To do this, I run the program BoxCryptor on my computer. Essentially, it encrypts the contents of my Dropbox folder and creates another folder on my computer where I can access the unencrypted versions of client files. This allows me to protect client documents both on my computer and in the cloud. Dropbox can see only that a specific file exists, they can't open and view the contents of the file. Additionally, without the BoxCryptor program running, you could be sitting at my computer and not be able to view or open client files because they would be encrypted.",
      "Fifth, BackBlaze and Dropbox both use an additional layer of security called two-factor authentication. In BackBlaze, a code is sent to my phone when I log into their system. Even if a thief has my computer, and my BackBlaze password, they will not be able to access the data stored with BackBlaze without the code from my phone. Dropbox sends a similar code whenever a login is attempted from an unauthorized computer or mobile device.",
      "Lastly, I also back up my computer's hard drive to an external hard drive. The data on this drive is also encrypted. Only I have the encryption key so the data on the drive would be inaccessible to a thief.",
      "Please know that I take the security of your personal information very seriously. If you have any questions about your documents or my security procedures, please feel free to call the office or use the contact form on this website.",
    ],
  },
  {
    year: "2016",
    month: "05",
    slug: "why-you-need-to-be-aware-of-your-digital-footprint",
    title: "Why You Need to Be Aware of Your Digital Footprint",
    date: "May 9, 2016",
    excerpt: "As our mobile phones and social media become increasingly integrated into our lives, the danger exists that these technologies could be used against you in court.",
    body: [
      "As our mobile phones and social media become increasingly integrated into our lives, the danger exists that these technologies could be used against you in court. By now, most everyone has heard of the FBI's attempt to have Apple unlock a terrorist's iPhone. What most people don't consider is there own digital life \u2013 or footprint \u2013 and how it could be used against them in court.",
      "I could write a long article about the dangers of Facebook in a family law case. However, I think the following infographic by a Maryland law firm better illustrates the dangers posed in a family law case by all aspects of your digital like \u2013 not just Facebook.",
      "In a litigated divorce case, all of your social media posts, voice messages, text messages, videos, call logs, photos, blog comments and more are discoverable by your spouse's lawyer.",
    ],
  },
  {
    year: "2016",
    month: "05",
    slug: "are-you-making-your-divorce-more-expensive-than-it-has-to-be",
    title: "Are You Making Your Divorce More Expensive Than it Has to Be?",
    date: "May 24, 2016",
    excerpt: "There is little doubt that getting divorced is expensive. Even if you have a small fortune to spend on your divorce case, who wants to spend their money that way? Fortunately,\u2026",
    body: [
      "There is little doubt that getting divorced is expensive. Even if you have a small fortune to spend on your divorce case, who wants to spend their money that way? Fortunately, there are a few things you can do to try to keep the costs down.",
      "Don't Spend to Much Time on the Small Stuff",
      "Don't spend to much time (and, as a result, money) trying to split the marital assets exactly 50/50. Some couples will spend hours at mediation with their lawyers arguing over dishes, linens, kitchen equipment, etc. Most often, your time is better spent discussing the major assets, such as financial accounts, real estate, and vehicles. Also, you should realize that very often the marital assets are not divided 50/50 because one party takes on more than 50% of the marital debt.",
      "Don't Over-Involve your Lawyer",
      "I, like most Family Law attorneys, want to help my clients. However, there are only so many hours in each day and I have to charge for the time I spend on a client's case. Every once-in-a-while a client will think that their spouse will be required to pay their attorney fees, so they feel free to call as often as they want with any question they can think of. As you might expect, this gets very expensive \u2013 very quickly. At a mediation, one of the last issues discussed is usually attorney fees. As a result, most people end up paying their own attorney fees. A better course of action would have been for the client to call as little as possible with only the most important questions. Of course, it's hard to determine which are the \"most important questions.\"",
      "Make a Budget",
      "Do not overspend while involved in a divorce case. In general, this is not the time to take big vacations or make big purchases (homes or vehicles). Figure out what your living expenses will be after the divorce. Also estimate what your income will be, using a high estimate if you might be paying alimony or a low estimate if you may be receiving alimony. If you want to stay in the marital home, but cannot afford to do so after looking at your budget, talk to your spouse about selling the home.",
      "Underlying each of these ideas is the idea that you need to be flexible \u2013 even at the start of your case. However, you should not be the only one who is flexible. To help you walk this fine line, be sure to speak with an experienced family law attorney.",
    ],
  },
  {
    year: "2016",
    month: "05",
    slug: "recent-study-suggests-equal-time-sharing-is-better-for-kids-health",
    title: "Recent Study Suggests Equal Time Sharing is Better for Kid's Health",
    date: "May 27, 2016",
    excerpt: "A recent study analyzed the living arrangements of 147,839 children in the sixth and ninth grades. Of the children studied, 69% lived at home with both parents, 21% lived mostly\u2026",
    body: [
      "A recent study analyzed the living arrangements of 147,839 children in the sixth and ninth grades. Of the children studied, 69% lived at home with both parents, 21% lived mostly or entirely with one parent, and 10% spent about equal time with both parents.",
      "Not surprisingly, the children who lived with both parents had the fewest psychosomatic health issues \u2013 headaches, upset stomach, trouble sleeping, problems with concentration, loss of appetite, and sadness.",
      "The children who lived with only one parent experienced these problems the most \u2013 especially trouble sleeping and headaches. This group was also the least satisfied with their relationship with their parents. Children who spent about equal time with both parents had fewer of these health problems than the children who lived primarily with one parent. This group was only slightly less satisfied with their relationship with their parents as compared to the group of children who lived with both parents in the same home.",
      "The researchers wrote that the data suggests that \"the potential stress from living in two homes could be outweighed by the positive effects of close contact with both parents.\"",
      "In my experience, having practiced family law for 16 years, there has been a huge change in the attitudes judges have toward equal (or nearly equal) time sharing. 16 years ago, judges were hesitant to allow equal time sharing even when the parents agreed that such an arrangement was in the best interests of their child. Now, an equal time sharing agreement is very often viewed as a positive for everyone.",
      "The data in this study did not include data about the level on conflict within the child's family. It is certainly possible that a child would experience more of these health problem when living with both parent who often argued.",
    ],
  },
  {
    year: "2016",
    month: "05",
    slug: "who-gets-divorced-in-america",
    title: "Who Gets Divorced in America?",
    date: "May 30, 2016",
    excerpt: "Everyone has heard the divorce statistic that 50% of marriage end in divorce. That is certainly not the case these days.",
    body: [
      "Everyone has heard the divorce statistic that 50% of marriage end in divorce. That is certainly not the case these days. In fact, the divorce rate in the US has been steadily (but slowly) declining since the early 1980s. If current trends hold, the divorce rate could soon be at 33%. However, the divorce rate for some groups is much higher.",
      "Researchers analyzed the number of times a person gets married or divorced over their lifetime. Obviously, you can't get divorced unless you've also been married, so the researchers considered the number of times a person had been married or divorced more than once over the course of their life. The results varied bases on gender, education, and ethnicity.",
      "The Results:",
      "- High school or less (all ethnic groups): 39% of men, 37% of women have been married or divorced more than once.\n- Bachelor's degree (all ethnic groups): 28% of men, 29% of women\n- White (all education levels): 36% of men, 38% of women\n- Black (all education levels): 42% of men, 42% of women\n- Hispanic (all education levels): 27% of men, 30% of women\n- Asian (all education levels): 16% of men, 18% of women\n- Native American (all education levels): 44% of men, 45% of women",
    ],
  },
  {
    year: "2016",
    month: "05",
    slug: "what-happens-to-your-mortgage-in-a-divorce",
    title: "What Happens to Your Mortgage in a Divorce?",
    date: "May 31, 2016",
    excerpt: "Often there is confusion surrounding a marital home in a divorce case. There are two different things to consider:",
    body: [
      "Often there is confusion surrounding a marital home in a divorce case. There are two different things to consider:",
      "- the deed to your home \u2013 i.e. who has the legal right to live there, and\n- the mortgage on your home \u2013 i.e. who has the legal obligation to pay for the home.",
      "At a final hearing, a judge can decide who (if anyone) will be able to live in the marital home. For example, suppose that the Husband and the Wife each want to remain in the marital home with their child. At the final hearing, the judge decides that the Wife can stay in the marital home with the child. In order to make the home the Wife's property rather than the now-divorced couple's joint property, the judge could order the Husband to sign a quitclaim deed that would transfer any legal interest he had in the home to his ex-Wife. The judge could also transfer the legal ownership of the home from the couple to the Wife as part of the final judgment.",
      "This is not the end of the analysis of the marital home. Typically, the party who is awarded the home has to pay for the home. So, in my hypothetical, the Judge would require the Wife to make the monthly mortgage payments. However, since the mortgage company is not a party to the divorce case, they are not bound by the judge's order that the Wife makes the payments. If the Wife fails to make the mortgage payments, they can sue her \u2013 but they can also sue the Husband. (This scenario assumes that the Husband and Wife were both obligated to pay for the home under the terms of the mortgage). This puts the Husband in the unfortunate position of having his credit affected by the actions (or inaction) of the Wife.",
      "In order to avoid this scenario in a divorce, it is important to consider the possibility of selling the home or refinancing the mortgage in order to remove a spouse's name from the mortgage. When considering what to do with a marital home, think of the following points:",
      "Selling the home is often the best option.",
      "This is often the best option since it results in a clean break. Selling the home removes a large financial connection between the Husband and Wife. Even if you assume that the party remaining in the home make all the payments, the other party could find it difficult to buy a home since they are still legally obligated to pay the mortgage of the former marital home. This is not a popular situation.",
      "Also included in this option is a re-financing of the mortgage into one party's name alone. Essentially, this is still a sale of the home \u2013 but only to the person who is living in the home.",
      "Can you afford to stay in the home?",
      "When possible, it is important to consider a re-financing prior to the end of your case. Both parties may agree on a re-financing of the home, but that does not mean that you will qualify for the loan from a bank.",
      "Is there any equity in the home?",
      "All too often, you may discover that after a sale of your home, you still owe the bank. This situation is called being \"upside-down\" or \"underwater.\" In this situation, it is sometimes better for one of the spouses to remain in the home \u2013 and paying for it \u2013 rather than selling the home and obligating each spouse for thousands of dollars in debt. It may be better to continue your financial connection to your ex rather than incur a huge debt. Hopefully, the value of the home will eventually increase enough so that it can be sold without incurring the additional debt.",
      "Due to the emotions and volume of decisions that need to be made in a divorce case, these mortgage issues often get overlooked. Please consider consulting with a family law attorney about these complicated mortgage issues.",
    ],
  },
  {
    year: "2016",
    month: "06",
    slug: "your-teen-during-divorce",
    title: "Your Teen During Divorce",
    date: "June 2, 2016",
    excerpt: "Divorce is difficult for children of any age. However, due to the potential for risky behavior in response to their parent's divorce, teenage children present a unique set of\u2026",
    body: [
      "Divorce is difficult for children of any age. However, due to the potential for risky behavior in response to their parent's divorce, teenage children present a unique set of concerns. The following is a list of \"Do's\" and \"Don't\" to think about as you try to get your teen through a difficult time.",
      "What Not to Do",
      "- Don't talk bad about your ex. In Florida, at least, this activity is prohibited and is standard language in Parenting Plans. Generally, it is better that your teen has a relationship with both parents. If you need someone to talk to about the divorce, speak with a friend or a counselor \u2013 not your child.\n- Don't use your child as a go-between. Don't use your teen to relay messages back and forth between you and your ex. This puts the teen in the awkward position of delivering bad news or being part of an argument that they otherwise would not be involved in. Also, don't use your child to ask for or deliver child support payments.\n- Don't force a teen to talk about the divorce until they are ready. Let them know that you are available to talk when they are ready.\n- Don't discourage or prohibit contact between the teen and your ex. As I've already mentioned, it is generally in the teen's best interest to have a relationship with both parents. Do not threaten to withhold access to the teen as a bargaining child in an argument with your ex. For example, do not restrict access to the teen if your ex's child support payment is late. Besides being potentially bad for your child, such conduct is prohibited by the statutes.\n- Don't expose your teen to your new love interest too soon. To much change to quickly can be a bad thing. The divorce has potentially pushed a teen to his/her limits. Adding your new love interest to the equation will probably not help.",
      "What to Do",
      "- Play the Long Game. The more you stay connected to your child, the more likely they will come to you when they really need help.\n- Stay positive. As your teen's #1 role model, it is important to stay positive. This is a time for your teen to see taking the high road, being resilient, and having a sense of humor even when faced with difficult times.\n- Be a patient and compassionate parent, not their friend. Your teen will need your patience and compassion as they figure out \"the new normal.\" Part of that means holding them accountable and not allowing risky behaviors.\n- Keep up their routine. This will help give your teen a sense of normalcy in an otherwise chaotic time.\n- Get them help if they need it. It is unlikely that you can be everything to your teen. Find your teen other good adult role models. Such people could be extended to family members, teachers, clergy, etc.\n- Take care of yourself. You can't be as effective a parent as you could be if you are dealing with your own issues. Be sure to eat right, get enough sleep and talk to someone if you need to.",
    ],
  },
  {
    year: "2016",
    month: "06",
    slug: "diet-after-divorce",
    title: "Diet After Divorce",
    date: "June 7, 2016",
    excerpt: "A recent article in the Wall Street Journal discussed a new study of the diets of men and women after divorce.",
    body: [
      "A recent article in the Wall Street Journal discussed a new study of the diets of men and women after divorce.",
      "The researchers assessed the health of 11,577 people who ranged in age from 40 to 80. The participant's health was assessed from 1993 to 1997 and a second time from 1998 to 2002. As part of the assessment, the participants were asked about their consumption of fruits and vegetables.",
      "As of the first assessment, 89% of the men and 78% of the women were married. Between the time of the second assessment, 2.4% of the men and 4.5% of the women became divorced, separated or widowed.",
      "The divorced, separated or widowed men reported a 25% reduction in their consumption of fruits and vegetables as compared to the men who remained married. However, the divorced, separated or widowed women's diets remained the same.",
      "Also, alcohol consumption was about equal for the two groups of men. For divorced, separated or widowed women, alcohol intake went down by about one drink per week as compared to those women who remained married.",
      "The researchers found the difference in the two groups of men significant because previous studies have shown a relationship between the reduced consumption of produce and a greater risk of cardiovascular disease, cancer, and Type 2 diabetes.",
    ],
  },
  {
    year: "2016",
    month: "06",
    slug: "vacation-tips-for-divorced-or-separated-parents",
    title: "Vacation Tips for Divorced or Separated Parents",
    date: "June 11, 2016",
    excerpt: "School's out for the summer. That means it's time for family vacations. Unfortunately, that often means stress for parents and children.",
    body: [
      "School's out for the summer. That means it's time for family vacations. Unfortunately, that often means stress for parents and children. The following tips may help the parents avoid conflict and allow the children to have a better vacation.",
      "To try to avoid the stress of summer vacation, consider the following tips:",
      "- **Plan your trips well in advance.** Don't wait until the summer has begun to start discussing summer vacation plans. Many disagreement and conflicts can be avoided simply by planning your trips in advance. In Florida, a standard Parenting Plan, sets deadline for the notification of travel plans. Try to give more notice than the Parenting Plan requires.\n- **Tell the other parent of your trip details.** Notification goes hand in hand with planning. If you've planned a trip, tell the other parent about it as soon as possible. I always tell clients to confirm any plans you make with the other parent by email. That way, both parents know that there is evidence of the notification and the agreement.\n- **Make a checklist**. Make sure you have what you need. Include things like medication, insurance information, favorite toys and passports (for international travel).\n- **Don't make vacations a competition**. Typically, children just want to be with their parents and have fun. Don't turn your choice of activity or destination into a competition with the other parent. This can cause a child to have less fun with one parent so that they do not feel like they are disappointing the other parent.\n- Tell your children about your plans. Both parents telling their child together about the vacation plans will help the child understand that the parents come up with these plans together. Tell your children that they will have fun with the other parent and that that make you happy as well.",
    ],
  },
  {
    year: "2016",
    month: "06",
    slug: "facts-about-high-conflict-divorce",
    title: "Facts about High Conflict Divorce",
    date: "June 20, 2016",
    excerpt: "A High Conflict Divorce is a divorce where the parties are essentially at war and use their lawyers and the court system as their weapons.",
    body: [
      "A High Conflict Divorce is a divorce where the parties are essentially at war and use their lawyers and the court system as their weapons. The parties typically recognize (or are told) very early in the process that waging this type of \"war\" will be very expensive. They don't care. A recent article discusses some of the traits common to high conflict divorce.",
      "- **The High Cost of High Conflict Divorce.** Substantial savings can be had by choosing an alternative dispute resolution method \u2013 such as mediation \u2013 rather than litigation. The Associated Press has reported that high conflict litigation costs an average of $77,746. Mediating a high conflict case, rather than litigating it, has an average cost of $6,600.\n- **High Conflict cases have a higher rate of violence**. Of course, not all high conflict cases involve violence. But violence is more common in high conflict cases than in cases where the parties are able to rationally discuss the issues that come up in a divorce case (time-sharing, child support, asset/debt division, alimony, etc.).\n- **Mediation is more appropriate than Litigation for High Conflict cases.** High conflict cases often result because there are either (a) so many issues that need to be resolved, or (2) issues that seemingly have no middle ground (such as issues involving children). Other than the cost savings, mediation allows the parties to design an agreement that suits many (but not all) of their needs. In my experience, parties will spend much more time at a mediation discussing how to design a settlement than the judge will spend making decisions about their case. It's not that the judges don't care, it's that they are so busy they simply don't have the time to give your case the same amount of thought that you can give it at a mediation. Also, there are some things a judge would never order after a trial, but the parties can do by agreement.",
    ],
  },
  {
    year: "2016",
    month: "06",
    slug: "signs-your-marriage-is-worth-saving",
    title: "Signs Your Marriage is Worth Saving",
    date: "June 24, 2016",
    excerpt: "Usually once each month, I get a call from a potential client who basically asks me if they should get divorced.",
    body: [
      "Usually once each month, I get a call from a potential client who basically asks me if they should get divorced. My general rule is that I will not encourage people to get divorced. If you want to get divorced, I'm here to help. But I don't want to be the reason that couples divorce.",
      "The exception to that rule is when a couple has clearly moved on and are already living separate lives. In that situation, waiting to divorce very often complicates the inevitable divorce.",
      "I recently came across an article that listed 9 signs that your marriage is worth saving. Many of these signs are fairly obvious, but they are still quite valid. Read through all of them by following the link below, but the major ones (in my opinion) are:",
      "- You still feel you are respected in the marriage\n- Both spouses are willing to put in the work to save the marriage,\n- You can't imagine your life without your spouse\n- The spark is gone, but you think you can get it back\n- You still enjoy spending time together",
      "In order to get divorced in Florida, you must tell the judge that your marriage is irretrievably broken \u2013 broken and can't be fixed. If you think your marriage fits some of the situations above, your marriage not be broken beyond repair.",
    ],
  },
  {
    year: "2016",
    month: "07",
    slug: "what-happens-to-an-ira-or-401k-in-a-divorce-in-florida",
    title: "What happens to an IRA or 401k in a divorce in Florida?",
    date: "July 8, 2016",
    excerpt: "Question: What happens to an IRA or 401k in a divorce in Florida?",
    body: [
      "Question: What happens to an IRA or 401k in a divorce in Florida?",
      "An IRA or 401(k) are retirement accounts that offer the benefit of deferring income tax to the future. Typically, these accounts are marital assets to the extent they were created or contributed to during the marriage.",
      "Generally, three situations arise involving these types of retirement accounts. The first situation is when the account is created and contributed to during the marriage. In this situation, the entire account is marital property and can be divided between the parties by the judge.",
      "The second situation is when a spouse has a retirement account prior to the marriage and does not add to it during the marriage. In this situation, the account is not marital property and it will not be divided between the parties by the judge.",
      "The third situation is when a spouse has a retirement account prior to the marriage and contributes to the account during the marriage. In this situation, only the portion of the account that was created during the marriage is considered marital property subject to division by the court.",
      "For example, suppose that just prior to your marriage, you have an IRA with $50,000 in it. While married, you continue contributing to the account. When you get divorced, there is now $75,000 in the account, In this situation, only $25,000 is marital property since it was added to the account during the marriage.",
      "Often each account is not divided, even if they are all marital accounts. The spouses may still be left with roughly equivalent values in their retirement accounts, but this can sometimes be accomplished by making a single transfer instead of multiple transfers.",
    ],
  },
  {
    year: "2016",
    month: "07",
    slug: "why-should-a-couple-getting-a-divorce-consider-mediation",
    title: "Why Should a Couple Getting a Divorce Consider Mediation",
    date: "July 8, 2016",
    excerpt: "Transcript of video:",
    body: [
      "Transcript of video:",
      "First off, you don't need to mediate your case if you already have an agreement. In that case, you should hire an attorney to make sure the papers are prepared correctly and to quickly guide your case through the court system.",
      "If you don't already have an agreement, you can benefit from mediation in three ways.",
      "The first benefit is the lower cost. A successful mediation costs far less than litigation. While the cost of both mediation and litigation are based on hourly rates, a mediation takes far less time than a litigated case.",
      "The second benefit is time. A successful mediation will end your case almost immediately. A litigated case can take will over a year and involve many hearings, the production of documents, and perhaps a deposition.",
      "The third benefit of mediation is the agreement itself. At a mediation, you can use much more creative solutions to create your Final Judgment. You will be able to spend the time that a judge can't spend and come up with an agreement that has advantages for both sides.",
    ],
  },
  {
    year: "2016",
    month: "07",
    slug: "traveling-out-of-the-country-with-your-children",
    title: "Traveling out of the Country with your Children",
    date: "July 13, 2016",
    excerpt: "If you are thinking about an international trip with your child and you are not married to the child's other parent, there are a few steps you need to take to obtain the necessary\u2026",
    body: [
      "If you are thinking about an international trip with your child and you are not married to the child's other parent, there are a few steps you need to take to obtain the necessary permission of the child's other parent.",
      "In fact, each country has its own requirements for children traveling with only one parent \u2013 even if the parents are married. If you are planning such a trip, it is very important that you consult with the U.S. State Department to learn of the various requirements imposed by foreign countries.",
      "The common requirements for international travel with children include:",
      "- A valid passport for the child. There are varying requirements for the issuance of a passport based on the age of the child.\n  - Children under 16 \u2013 passport applications should be submitted in person by both parents and the child at a passport agency or authorized passport application acceptance facility. If both parents cannot be present, there are additional parental consent documentation requirements.\n  - Children 16 and 17 \u2013 passport applications may be submitted by the child alone if they have their own identification. It is recommended that at least one parent appears with the child to show parental awareness. Generally, a passport will not be issued to a 16 or 17-year-old child if a parent has notified the State Department in writing that they object to the issuance of a passport.\n- A Consent Form that has been signed by the other parent which references the specific trip you are taking. It is recommended that you use and have the International Travel Child Consent Form notarized.",
      "In my practice, most Parenting Plans entered in the last 8 years contain language that allows international travel. Additionally, there are almost always notification provisions that detail when a specific itinerary must be provided to the other parent.",
      "If your Parenting Plan does not include any provisions for international travel, and the other party objects to international travel, you can ask for court permission. Be sure to request permission about 6 months prior to your trip due to delays with the judge's schedule and the time it takes to process your passport application.",
    ],
  },
  {
    year: "2016",
    month: "09",
    slug: "an-explanation-of-a-florida-child-support-guidelines-worksheet",
    title: "An Explanation of a Florida Child Support Guidelines Worksheet",
    date: "September 16, 2016",
    excerpt: "I get a lot of phone calls from people who recently attended a hearing where their child support obligation was calculated.",
    body: [
      "I get a lot of phone calls from people who recently attended a hearing where their child support obligation was calculated. The number one complaint is that they are not sure that the calculation is correct. They tell me that they were presented with a piece of paper with a lot of numbers on it \u2013 but no explanation about what those numbers mean.",
      "In this short video, I display a Child Support Guidelines Worksheet and walkthrough \u2013 part by part \u2013 what the various numbers mean and how they impact the calculation.",
      "I have many other F.A.Q. videos that offer a more in-depth discussion of child support, income, and deductions.",
      "Transcript of Video:",
      "I'm going to walk through what all these numbers mean in a Child Support Guidelines Worksheet. Hopefully, so you can better understand what is going on here. There are a lot of numbers. Only a very few are actually input into the system.",
      "This is a sample worksheet, not an actual client's worksheet. But this is more in line with what you will see at a court hearing, rather than the Child Support Guidelines Worksheet that the Supreme Court of Florida puts on their website.",
      "The first thing to notice is the number of children. The combined number of children. Here we have two (2) children. And they are living primarily with the Wife. Zero of the children living with the Husband. The next data that is input in the first section up here is in the income section. It shows a Wife with $3,109 of monthly income, and a Husband with $5400 of monthly income. It totals these numbers up to $8,509. These other lines here are for other ways you can make money. Basically they are all treated the same except for non-taxable income \u2013 which generally only comes up in a military context (but there are others). So the difference between the $8,509 and the $7,285 are the various deductions and this is what the rest of this side of the worksheet is talking about. It lists the various deductions \u2013 alimony payments, taxes, and other main ones union \u2013 dues, mandatory retirement plans, parent's health insurance cost (but not the children's, that is treated somewhere else). But the parent's health insurance cost as well as child support that is ordered and paid in other cases \u2013 not this case, but is ordered and paid in other cases.",
      "Each parent's net income is calculated and then it's added up to the $7,285 \u2013 and that's the number that is reflected on the next screen with the minimum child support need of $1,921.",
      "OK, so to review, the only numbers input on the left side of the screen were the number of children, the income of the Wife, the income of the Husband \u2013 nothing was input as any alimony payment made by either party. The taxes are calculated automatically, and there are no other deductions used. The numbers here at the bottom are all automatically calculated. And that gets us to the other side where we initially see the minimum child support need of $1,921.",
      "So starting on this side, the numbers that are input are simply the number of overnights that the children are going to have with the Husband. Based on the minimum child support need of $1921, the two (2) next numbers get divided up based on the percentages of income. So, in this situation, the Husband would typically pay $1108 a month in child support. That's not going to be the case here because of the number of nights with the children. The law requires a reduction in his child support if he spends more than 20% of the nights with the children. Here is shows you his percentage \u2013 27.4%. So that will provide, due to some interesting math provided by the statute, a pre-adjustment transfer \u2013 so that's his base child support amount based on his number of nights and his income \u2013 of $873.",
      "Next, we go down to a couple of expenses that are counted in a child support calculation. First, this hypothetical couple pays $450 a month in daycare costs and $350 a month in medical. And here you can see that the Wife pays the child care and the Husband pays the medical. Each is responsible for only a portion of those numbers even though they pay the entire amount of each one. The Wife is responsible for 42.3% of both costs. And the Husband is responsible for 57.7% of both costs. So instead of having the Wife pay some money to the Husband and the Husband paying some money to the Wife, there's only one transfer and that's the $111.68 that the Husband pays in additional child support due to these expenses. We add that to the pre-adjustment transfer and you have him final child support amount of $985.06.",
    ],
  },
  {
    year: "2017",
    month: "01",
    slug: "alimony-reform-is-coming-to-florida-maybe",
    title: "Alimony Reform is Coming to Florida \u2013 maybe",
    date: "January 27, 2017",
    excerpt: "Over the last few years, there have been various attempts to \"reform\" Florida alimony laws. In April 2016, Governor Scott vetoed a bill due to a provision that had to do with a\u2026",
    body: [
      "Over the last few years, there have been various attempts to \"reform\" Florida alimony laws. In April 2016, Governor Scott vetoed a bill due to a provision that had to do with a presumption that 50/50 time-sharing schedule was in the best interest of children.",
      "With the beginning of a new legislative session, a version of a new alimony reform bill has been submitted to both the Senate and House of Representatives. Of course, both bills are subject to amendment while working their way through the legislative process.",
      "The most prominent part of the proposed law is the establishment of alimony guidelines. Currently, judges have the discretion to award alimony after consideration of various statutory factors. The alimony guidelines would provide judges with a range for the amount and duration of alimony.",
      "The low end of the range would be calculated as follows: .015 x (years of marriage) x (difference in the monthly gross incomes of the parties).",
      "The high end of the range would be calculated as follows: .020 x (years of marriage) x (difference in the monthly gross incomes of the parties).",
      "For purposes of calculating these values, the maximum duration of a marriage is 20 years. However, if the duration of the alimony is 50% or less of the duration of the marriage, then the Court shall use the actual duration of the marriage (up to a maximum of 25) when calculating the high end of the range.",
      "The presumptive duration of the alimony award is between 25% and 75% of the duration of the marriage.",
      "Under the bill, there would be a presumption against alimony where the marriage lasted less than 2 years.",
      "As an example, suppose that a Husband and Wife have been married for 18 years and the Husband earns $4000 per month more than the Wife. The presumptive range of the Husband's alimony payments would be between $1080 and $1440 and the presumptive duration would be between 4.5 years and 13.5 years.",
      "A court could deviate from these guidelines if, after considering all the statutory factors, it found that the application of the ranges was inappropriate or inequitable.",
    ],
  },
];

export function findPost(year: string, month: string, slug: string): BlogPost | undefined {
  return posts.find((p) => p.year === year && p.month === month && p.slug === slug);
}
